-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 13:59:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`FILM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FILM` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FILM` (
  `IdFilm` INT NOT NULL AUTO_INCREMENT,
  `NomFilm` VARCHAR(45) NOT NULL,
  `DureeFilm` DECIMAL(500) NOT NULL DEFAULT en minute,
  `DateSortie` DATE NOT NULL,
  PRIMARY KEY (`IdFilm`),
  UNIQUE INDEX `idFILM_UNIQUE` (`IdFilm` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GENRE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GENRE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GENRE` (
  `IdGenre` INT NOT NULL AUTO_INCREMENT,
  `NomGenre` VARCHAR(100) NOT NULL,
  `TypePublic` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdGenre`),
  UNIQUE INDEX `IdGenre_UNIQUE` (`IdGenre` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
