-- MySQL Script generated by MySQL Workbench
-- Thu Jul 23 11:18:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetlunettes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetlunettes` ;

-- -----------------------------------------------------
-- Schema projetlunettes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetlunettes` DEFAULT CHARACTER SET utf8 ;
USE `projetlunettes` ;

-- -----------------------------------------------------
-- Table `projetlunettes`.`typeUtilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetlunettes`.`typeUtilisateur` ;

CREATE TABLE IF NOT EXISTS `projetlunettes`.`typeUtilisateur` (
  `idTypeUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nomTypeUtilisateur` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTypeUtilisateur`),
  UNIQUE INDEX `idTypeUtilisateur_UNIQUE` (`idTypeUtilisateur` ASC) VISIBLE,
  UNIQUE INDEX `nomTypeUtilisateur_UNIQUE` (`nomTypeUtilisateur` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetlunettes`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetlunettes`.`adresse` ;

CREATE TABLE IF NOT EXISTS `projetlunettes`.`adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `codePostal` INT NOT NULL,
  `nomVille` VARCHAR(255) NOT NULL,
  `nomPays` VARCHAR(255) NOT NULL,
  `adresse1` VARCHAR(255) NOT NULL,
  `adresseComplementaire` VARCHAR(255) NULL,
  PRIMARY KEY (`idAdresse`),
  UNIQUE INDEX `idAdresse_UNIQUE` (`idAdresse` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetlunettes`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetlunettes`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `projetlunettes`.`utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nomUti` VARCHAR(255) NOT NULL,
  `prenomUti` VARCHAR(255) NOT NULL,
  `emailUti` VARCHAR(100) NOT NULL,
  `mdpUti` VARCHAR(255) NOT NULL,
  `telUti` INT NOT NULL,
  `typeUtilisateur_idTypeUtilisateur` INT NOT NULL,
  `adresse_idAdresse` INT NOT NULL,
  PRIMARY KEY (`idUtilisateur`),
  UNIQUE INDEX `idUtilisateur_UNIQUE` (`idUtilisateur` ASC) VISIBLE,
  INDEX `fk_Utilisateur_Type Utilisateur1_idx` (`typeUtilisateur_idTypeUtilisateur` ASC) VISIBLE,
  INDEX `fk_Utilisateur_Adresse1_idx` (`adresse_idAdresse` ASC) VISIBLE,
  CONSTRAINT `fk_Utilisateur_Type Utilisateur1`
    FOREIGN KEY (`typeUtilisateur_idTypeUtilisateur`)
    REFERENCES `projetlunettes`.`typeUtilisateur` (`idTypeUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_Adresse1`
    FOREIGN KEY (`adresse_idAdresse`)
    REFERENCES `projetlunettes`.`adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetlunettes`.`lunettes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetlunettes`.`lunettes` ;

CREATE TABLE IF NOT EXISTS `projetlunettes`.`lunettes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomLunettes` VARCHAR(255) NOT NULL,
  `descriptionLunettes` TEXT(10000) NOT NULL,
  `prixLunettes` DECIMAL(5,2) NOT NULL,
  `tailleLunettes` VARCHAR(255) NOT NULL,
  `imageLunettes` VARCHAR(255) NOT NULL,
  `dateLunettes` DATETIME NOT NULL,
  `qteLunettes` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetlunettes`.`ceinture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetlunettes`.`ceinture` ;

CREATE TABLE IF NOT EXISTS `projetlunettes`.`ceinture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomCeinture` VARCHAR(255) NOT NULL,
  `descriptionCeinture` TEXT(10000) NOT NULL,
  `prixCeinture` DECIMAL(5,2) NOT NULL,
  `imageCeinture` VARCHAR(255) NOT NULL,
  `dateAjoutCeinture` DATETIME NOT NULL,
  `qteCeinture` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetlunettes`.`accessoire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetlunettes`.`accessoire` ;

CREATE TABLE IF NOT EXISTS `projetlunettes`.`accessoire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomAccessoire` VARCHAR(255) NOT NULL,
  `descriptionAccessoire` TEXT(10000) NOT NULL,
  `prixAccessoire` DECIMAL(5,2) NOT NULL,
  `tailleAccessoire` VARCHAR(255) NULL,
  `tailleCeinture` VARCHAR(255) NOT NULL,
  `imageAccessoire` VARCHAR(255) NOT NULL,
  `dateAjoutAccessoire` DATETIME NOT NULL,
  `qteAccessoire` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetlunettes`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetlunettes`.`genre` ;

CREATE TABLE IF NOT EXISTS `projetlunettes`.`genre` (
  `idgenre` INT NOT NULL,
  `homme` VARCHAR(45) NULL,
  `femme` VARCHAR(45) NULL,
  `lunettes_id` INT NOT NULL,
  `ceinture_id` INT NOT NULL,
  `accessoire_id` INT NOT NULL,
  UNIQUE INDEX `idgenre_UNIQUE` (`idgenre` ASC) VISIBLE,
  PRIMARY KEY (`idgenre`),
  INDEX `fk_genre_lunettes1_idx` (`lunettes_id` ASC) VISIBLE,
  INDEX `fk_genre_ceinture1_idx` (`ceinture_id` ASC) VISIBLE,
  INDEX `fk_genre_accessoire1_idx` (`accessoire_id` ASC) VISIBLE,
  CONSTRAINT `fk_genre_lunettes1`
    FOREIGN KEY (`lunettes_id`)
    REFERENCES `projetlunettes`.`lunettes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genre_ceinture1`
    FOREIGN KEY (`ceinture_id`)
    REFERENCES `projetlunettes`.`ceinture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genre_accessoire1`
    FOREIGN KEY (`accessoire_id`)
    REFERENCES `projetlunettes`.`accessoire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetlunettes`.`panier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetlunettes`.`panier` ;

CREATE TABLE IF NOT EXISTS `projetlunettes`.`panier` (
  `idPanier` INT NOT NULL AUTO_INCREMENT,
  `utilisateur_idUtilisateur` INT NOT NULL,
  `genre_idgenre` INT NOT NULL,
  PRIMARY KEY (`idPanier`),
  INDEX `fk_panier_utilisateur1_idx` (`utilisateur_idUtilisateur` ASC) VISIBLE,
  INDEX `fk_panier_genre1_idx` (`genre_idgenre` ASC) VISIBLE,
  CONSTRAINT `fk_panier_utilisateur1`
    FOREIGN KEY (`utilisateur_idUtilisateur`)
    REFERENCES `projetlunettes`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_panier_genre1`
    FOREIGN KEY (`genre_idgenre`)
    REFERENCES `projetlunettes`.`genre` (`idgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
