-- MySQL Script generated by MySQL Workbench
-- Fri Apr 10 11:34:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detail` (
  `iddetail` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` TEXT(1000) NOT NULL,
  PRIMARY KEY (`iddetail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `idcontact` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(100) NOT NULL,
  `adresse1` VARCHAR(255) NOT NULL,
  `adresse2` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(100) NOT NULL,
  `pays` VARCHAR(100) NOT NULL,
  `codepostal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcontact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `idlocation` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomloc` VARCHAR(200) NOT NULL,
  `desloc` TEXT(1000) NOT NULL,
  `imgloc` VARCHAR(45) NOT NULL,
  `detail_iddetail` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idlocation`),
  INDEX `fk_location_detail_idx` (`detail_iddetail` ASC),
  CONSTRAINT `fk_location_detail`
    FOREIGN KEY (`detail_iddetail`)
    REFERENCES `mydb`.`detail` (`iddetail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
