-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 11:47:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `IdUtilisateur` INT NOT NULL,
  `NomUti` VARCHAR(150) NOT NULL,
  `PrenomUti` VARCHAR(150) NOT NULL,
  `EmailUti` VARCHAR(150) NOT NULL,
  `TelUti` VARCHAR(150) NOT NULL,
  `NumRue` INT NOT NULL,
  `NomRue` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`IdUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`type_utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`type_utilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`type_utilisateur` (
  `IdTypeUti` INT UNSIGNED NOT NULL,
  `NomTypeUti` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`IdTypeUti`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`adresse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`adresse` (
  `IdAdresse` INT NOT NULL,
  `CodePostal` INT NOT NULL,
  `NomVille` VARCHAR(150) NOT NULL,
  `NomPays` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IdAdresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `IdProduit` INT NOT NULL,
  `NomProduit` VARCHAR(100) NOT NULL,
  `NumRef` INT NOT NULL,
  `CodeBarre` VARCHAR(45) NOT NULL,
  `PrixProduit` DECIMAL(4,2) NOT NULL,
  `QteProduit` INT NOT NULL,
  PRIMARY KEY (`IdProduit`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
