-- MySQL Script generated by MySQL Workbench
-- Wed May 27 16:34:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema siteOP
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `siteOP` ;

-- -----------------------------------------------------
-- Schema siteOP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siteOP` DEFAULT CHARACTER SET utf8 ;
USE `siteOP` ;

-- -----------------------------------------------------
-- Table `siteOP`.`typeUtilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siteOP`.`typeUtilisateur` ;

CREATE TABLE IF NOT EXISTS `siteOP`.`typeUtilisateur` (
  `idTypeUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nomTypeUtilisateur` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTypeUtilisateur`),
  UNIQUE INDEX `idTypeUtilisateur_UNIQUE` (`idTypeUtilisateur` ASC) VISIBLE,
  UNIQUE INDEX `nomTypeUtilisateur_UNIQUE` (`nomTypeUtilisateur` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siteOP`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siteOP`.`adresse` ;

CREATE TABLE IF NOT EXISTS `siteOP`.`adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `codePostal` INT NOT NULL,
  `nomVille` VARCHAR(255) NOT NULL,
  `nomPays` VARCHAR(255) NOT NULL,
  `adresse1` VARCHAR(255) NOT NULL,
  `adresseComplementaire` VARCHAR(255) NULL,
  PRIMARY KEY (`idAdresse`),
  UNIQUE INDEX `idAdresse_UNIQUE` (`idAdresse` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siteOP`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siteOP`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `siteOP`.`utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nomUti` VARCHAR(255) NOT NULL,
  `prenomUti` VARCHAR(255) NOT NULL,
  `emailUti` VARCHAR(100) NOT NULL,
  `mdpUti` VARCHAR(255) NOT NULL,
  `telUti` INT NOT NULL,
  `typeUtilisateur_idTypeUtilisateur` INT NOT NULL,
  `adresse_idAdresse` INT NOT NULL,
  PRIMARY KEY (`idUtilisateur`),
  UNIQUE INDEX `idUtilisateur_UNIQUE` (`idUtilisateur` ASC) VISIBLE,
  INDEX `fk_Utilisateur_Type Utilisateur1_idx` (`typeUtilisateur_idTypeUtilisateur` ASC) VISIBLE,
  INDEX `fk_Utilisateur_Adresse1_idx` (`adresse_idAdresse` ASC) VISIBLE,
  CONSTRAINT `fk_Utilisateur_Type Utilisateur1`
    FOREIGN KEY (`typeUtilisateur_idTypeUtilisateur`)
    REFERENCES `siteOP`.`typeUtilisateur` (`idTypeUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_Adresse1`
    FOREIGN KEY (`adresse_idAdresse`)
    REFERENCES `siteOP`.`adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siteOP`.`figurine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siteOP`.`figurine` ;

CREATE TABLE IF NOT EXISTS `siteOP`.`figurine` (
  `idFigurine` INT NOT NULL AUTO_INCREMENT,
  `nomFigurine` VARCHAR(255) NOT NULL,
  `prixFigurine` DECIMAL(3,2) NOT NULL,
  `genreFigurine` VARCHAR(255) NOT NULL,
  `imageFigurine` VARCHAR(255) NOT NULL,
  `dateAjoutFigurine` DATETIME NOT NULL,
  `qteFigurine` INT NOT NULL,
  PRIMARY KEY (`idFigurine`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siteOP`.`livre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siteOP`.`livre` ;

CREATE TABLE IF NOT EXISTS `siteOP`.`livre` (
  `idLivre` INT NOT NULL AUTO_INCREMENT,
  `titreLivre` VARCHAR(255) NOT NULL,
  `prixLivre` DECIMAL(3,2) NOT NULL,
  `genreLivre` VARCHAR(45) NOT NULL,
  `imageLivre` VARCHAR(255) NOT NULL,
  `dateAjoutLivre` DATETIME NOT NULL,
  `qteLivre` INT NOT NULL,
  PRIMARY KEY (`idLivre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siteOP`.`dvdBluray`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siteOP`.`dvdBluray` ;

CREATE TABLE IF NOT EXISTS `siteOP`.`dvdBluray` (
  `idDvd` INT NOT NULL AUTO_INCREMENT,
  `nomDvd` VARCHAR(255) NOT NULL,
  `prixDvd` DECIMAL(3,2) NOT NULL,
  `formatDvd` TINYINT(2) NULL,
  `imageDvd` VARCHAR(255) NOT NULL,
  `dateAjoutDvd` DATETIME NOT NULL,
  `qteDvd` INT NOT NULL,
  PRIMARY KEY (`idDvd`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siteOP`.`vetement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siteOP`.`vetement` ;

CREATE TABLE IF NOT EXISTS `siteOP`.`vetement` (
  `idVetement` INT NOT NULL AUTO_INCREMENT,
  `nomVetement` VARCHAR(255) NOT NULL,
  `prixVetement` DECIMAL(3,2) NOT NULL,
  `tailleVetement` VARCHAR(45) NOT NULL,
  `imageVetement` VARCHAR(45) NOT NULL,
  `dateAjoutVetement` DATETIME NOT NULL,
  `qteVetement` INT NOT NULL,
  PRIMARY KEY (`idVetement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siteOP`.`goodie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siteOP`.`goodie` ;

CREATE TABLE IF NOT EXISTS `siteOP`.`goodie` (
  `idGoodie` INT NOT NULL AUTO_INCREMENT,
  `nomGoodie` VARCHAR(255) NOT NULL,
  `prixGoodie` DECIMAL(3,2) NOT NULL,
  `imageGoodie` VARCHAR(45) NOT NULL,
  `dateAjoutGoodie` DATETIME NOT NULL,
  `qteGoodie` INT NOT NULL,
  PRIMARY KEY (`idGoodie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siteOP`.`panier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siteOP`.`panier` ;

CREATE TABLE IF NOT EXISTS `siteOP`.`panier` (
  `idPanier` INT NOT NULL AUTO_INCREMENT,
  `figurine_idFigurine` INT NULL,
  `livre_idLivre` INT NULL,
  `dvdBluray_idDvd` INT NULL,
  `vetement_idVetement` INT NULL,
  `goodie_idGoodie` INT NULL,
  PRIMARY KEY (`idPanier`),
  INDEX `fk_Panier_Figurine_idx` (`figurine_idFigurine` ASC) VISIBLE,
  INDEX `fk_Panier_Livre1_idx` (`livre_idLivre` ASC) VISIBLE,
  INDEX `fk_Panier_DVD & Bluray1_idx` (`dvdBluray_idDvd` ASC) VISIBLE,
  INDEX `fk_Panier_Vetement1_idx` (`vetement_idVetement` ASC) VISIBLE,
  INDEX `fk_Panier_Goodie1_idx` (`goodie_idGoodie` ASC) VISIBLE,
  CONSTRAINT `fk_Panier_Figurine`
    FOREIGN KEY (`figurine_idFigurine`)
    REFERENCES `siteOP`.`figurine` (`idFigurine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Panier_Livre1`
    FOREIGN KEY (`livre_idLivre`)
    REFERENCES `siteOP`.`livre` (`idLivre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Panier_DVD & Bluray1`
    FOREIGN KEY (`dvdBluray_idDvd`)
    REFERENCES `siteOP`.`dvdBluray` (`idDvd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Panier_Vetement1`
    FOREIGN KEY (`vetement_idVetement`)
    REFERENCES `siteOP`.`vetement` (`idVetement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Panier_Goodie1`
    FOREIGN KEY (`goodie_idGoodie`)
    REFERENCES `siteOP`.`goodie` (`idGoodie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siteOP`.`commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siteOP`.`commande` ;

CREATE TABLE IF NOT EXISTS `siteOP`.`commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `panier_idPanier` INT NOT NULL,
  `utilisateur_idUtilisateur` INT NOT NULL,
  UNIQUE INDEX `idType de produit_UNIQUE` (`idCommande` ASC) VISIBLE,
  PRIMARY KEY (`idCommande`),
  INDEX `fk_Commande_Panier1_idx` (`panier_idPanier` ASC) VISIBLE,
  INDEX `fk_Commande_Utilisateur1_idx` (`utilisateur_idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Commande_Panier1`
    FOREIGN KEY (`panier_idPanier`)
    REFERENCES `siteOP`.`panier` (`idPanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Utilisateur1`
    FOREIGN KEY (`utilisateur_idUtilisateur`)
    REFERENCES `siteOP`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
